### ISSUE TITLE
How to get profile from session

### ISSUE THREAD

**Issue by franklinjavier** [juhanakristian/remix-auth-microsoft#1]
Hi, I'm trying to get the profile from the session, but I don't understand how to do it following the readme.
Can you help, please?

**Comment by franklinjavier** [comment]
Minimal reproduce:


```tsx
// auth.server.ts
import { Authenticator } from 'remix-auth'
import { sessionStorage, getSession } from '~/services/session.server'
import { MicrosoftStrategy } from 'remix-auth-microsoft'

export let authenticator = new Authenticator<string>(sessionStorage)

let azdoStrategy = new MicrosoftStrategy(
  {
    clientID: process.env.MS_CLIENT_ID || '',
    clientSecret: process.env.MS_CLIENT_SECRET || '',
    callbackURL: 'http://localhost:3000/auth/microsoft/callback',
    tenant: process.env.MS_TENANT || '',
  },
  async ({ accessToken, extraParams, profile }) => {
    console.log({ accessToken, extraParams, profile }) // profile is ok here, i need to set session here? 
    return { accessToken, extraParams, profile }
  },
)

authenticator.use(azdoStrategy)

```

```tsx
// dashboard.tsx
import { LoaderFunction, useLoaderData } from 'remix'
import { getSession } from '~/services/session.server'
import { Layout } from '~/components/Layout'

export interface User {
  email: string
}

export let loader: LoaderFunction = async ({ request }) => {
  const user = await getSession(request.headers.get('Cookie'))
  return { user }
}
export default function Dashboard() {
  let data = useLoaderData()

  return <Layout>{JSON.stringify(data)}</Layout>
}
```

**Comment by juhanakristian** [comment]
Hi @franklinjavier and thanks for filing an issue!

The problem seems to be that the library isn't correctly returning `extraParams`. 

I will fix the issue with `extraParams` soon but in the meanwhile, if you remove the reference to `extraParams` from your verify callback you should be able to retrieve the profile using `getSession` or `authenticator.isAuthenticated`

**Comment by franklinjavier** [comment]
Now it works, thanks for the tip ;)

```js
const azdoStrategy = new MicrosoftStrategy(
  {
    clientID: process.env.MS_CLIENT_ID || '',
    clientSecret: process.env.MS_CLIENT_SECRET || '',
    callbackURL: 'http://localhost:3000/auth/microsoft/callback', // FIX ME
    tenant: process.env.MS_TENANT || '',
  },
  async ({ profile }) => {
    return profile
  },
)
```

**Comment by juhanakristian** [comment]
Actually what seems to happen is that since the return value of the verify callback is stored in the session cookie, if the return value is too big (over 4kb) it can't be saved and the cookie will have the previous value (`oauth2:state`).

While this is not a bug in remix-auth-microsoft, it is probably something that should be covered in the documentation.

Thanks again for reporting!

**Comment by franklinjavier** [comment]
Thanks mate

**Comment by bhargav-simejiya** [comment]
@franklinjavier

**Comment by bhargav-simejiya** [comment]
@franklinjavier 
Can you please share code snippet for required steps to integrate MS login?

**Comment by franklinjavier** [comment]
Sure

<img width="722" alt="image" src="https://user-images.githubusercontent.com/440220/180302736-70ccb2b1-0c16-4a82-b163-9c58dfee8ead.png">
<img width="648" alt="image" src="https://user-images.githubusercontent.com/440220/180302752-de9c72a1-d227-44fb-8d70-4931bcca4913.png">
<img width="619" alt="image" src="https://user-images.githubusercontent.com/440220/180302855-e54f9ac9-5ad8-4906-bb29-686bc308b4db.png">
<img width="687" alt="image" src="https://user-images.githubusercontent.com/440220/180302928-db373aa3-273c-4fba-ab0d-ef2b1d5b40da.png">
<img width="696" alt="image" src="https://user-images.githubusercontent.com/440220/180302954-d1e3a246-1102-4d28-96cc-f0ae60b7b71d.png">
<img width="841" alt="image" src="https://user-images.githubusercontent.com/440220/180303229-bf4efdb9-31d3-466a-9527-d97ed5040c14.png">
<img width="683" alt="image" src="https://user-images.githubusercontent.com/440220/180303338-08423b5f-6f2e-4eda-b0aa-d2f9a5fdaa88.png">

**Comment by franklinjavier** [comment]
You should add `prompt: 'select_account'`, because the @juhanakristian added this param recently
