### ISSUE TITLE
Inconsistent parameters in MicrosoftStrategyOptions

### ISSUE THREAD

**Issue by im-neil** [juhanakristian/remix-auth-microsoft#10]
Why don't the parameters for MicrosoftStrategyOptions in this GitHub repository match those in the npm package?

1) src/index.ts 
(this repository, version 1.03)

> export interface MicrosoftStrategyOptions {
  clientId: string;
  clientSecret: string;
  redirectUri: string;
  scope?: string;
  tenantId?: string;
  prompt?: string;
}

2) node_modules/remix-auth-microsoft/build/index.d.ts    
(version 1.03 as installed using _npm install remix-auth-microsoft remix-auth remix-auth-oauth2 @remix-run/server-runtime_)

> export interface MicrosoftStrategyOptions {
    clientID: string;
    clientSecret: string;
    callbackURL: string;
    scope?: string;
    tenant?: string;
    prompt?: string;
}

**Comment by juhanakristian** [comment]
Hi @im-neil and thanks for reporting the issue. The repository does indeed have different parameter names because they are going to be changed in the next version bu package version in the repo hasn't been updated yet. Sorry for the inconvenience.

**Comment by juhanakristian** [comment]
This has now been resolved in v2.0.0
