### ISSUE TITLE
remix-auth-oauth2 version 1.11 introduced a bug

### ISSUE THREAD

**Issue by bindermuehle** [juhanakristian/remix-auth-microsoft#23]
Bug Report

Description:

The recent update in remix-auth-oauth2 has introduced a conflict with the library's scope setting functionality. Prior to version 1.11.0, the library was setting the scope in a way that is now being overwritten.

Steps to Reproduce:

Navigate to the remix-auth-oauth2 GitHub repository: [Link to Repository](https://github.com/sergiodxa/remix-auth-oauth2/compare/v1.10.0...v1.11.0)
Review the changes made in the recent update to the library's scope setting mechanism.
Notice how the MicrosoftStrategy class sets this.scope as an array of scopes in the constructor: [Link to Code](https://github.com/juhanakristian/remix-auth-microsoft/blob/a12255753bf2f9c83635025973af3e715ae03fc2/src/index.ts#L91)
Current Behavior:

In version 1.11.0 of remix-auth-oauth2, the scope is being set based on the variable this.scope, which is an array in the library. However, the array is being concatenated to form a comma-separated list. This approach is not supported by Microsoft, as they require a space-separated list for the scope parameter.

Expected Behavior:

To ensure compatibility with Microsoft's requirements, it is suggested that the this.scope property be modified to a space-separated string. This adjustment will allow for seamless functionality with both version 1.10 and 1.11 of the library.

Code Reference:

The problematic lines of code can be found in the following locations:

MicrosoftStrategy class constructor: [Link to Code](https://github.com/juhanakristian/remix-auth-microsoft/blob/a12255753bf2f9c83635025973af3e715ae03fc2/src/index.ts#L91)
remix-auth-oauth2 library: [Link to Code](https://github.com/sergiodxa/remix-auth-oauth2/blob/593e397df11d3678fa4ad02935b44316ad2e5259/src/index.ts#L367)

Thanks in advance for your consideration

**Comment by juhanakristian** [comment]
I've published version 2.0.1 with the fix you provided. Thanks again @bindermuehle
